plus: add-sign-bold
dashboard: dashboard-browser-gauge
projects: app-window-layout
search: search-magnifier
account: app-window-user
lock: lock-key-1
settings: settings-cog
external: app-window-link
users: worldwide-web-users
filter: filter
chart: analytics-board-graph-line
calendar: calendar-date
check: form-validation-check-square-1
warning: alerts-warning-triangle
archive: archive-box
all: lists-bullets
folder_open: office-folder
pencil: edit-pencil
x: remove-delete-sign-bold
arrow_left: keyboard-arrow-return
upload: upload-brackets
clipboard: copy-paste-clipboard
mail: read-email-at-symbol
info: information-desk
key: login-logout-key
shield: security-shield-network
menu: menu-navigation-2
chevron_down: keyboard-keypad-pull-down
project_ruby: file-code
project_cfml: file-code-html
project_javascript: file-code-js-javascript
project_python: programming-code-idea
project_dotnet: app-window-source-code
