# frozen_string_literal: true

module ProjectPageCatalog::BasePages
  ATTRIBUTES = [
    {
      key: :overview,
      route_key: :overview,
      active_parent_key: nil,
      label: "Overview",
      header_label: "Project overview",
      description: "At-a-glance health and recent signals",
      icon_key: :home,
      navigation_group: :primary,
      menu_group: nil,
      order: 10,
      core: true
    }.freeze,
    {
      key: :inbox,
      route_key: :inbox,
      active_parent_key: nil,
      label: "Inbox",
      header_label: "Project inbox",
      description: "Errors that need triage",
      icon_key: :inbox,
      navigation_group: :primary,
      menu_group: nil,
      order: 20,
      core: true
    }.freeze,
    {
      key: :activity,
      route_key: :activity,
      active_parent_key: nil,
      label: "Events",
      header_label: "Project events",
      description: "Logs, metrics, transactions, and check-ins",
      icon_key: :events,
      navigation_group: :primary,
      menu_group: nil,
      order: 30,
      core: true
    }.freeze,
    {
      key: :insights,
      route_key: :insights,
      active_parent_key: nil,
      label: "Insights",
      header_label: "Project insights",
      description: "Trends and deeper telemetry exploration",
      icon_key: :insights,
      navigation_group: :primary,
      menu_group: nil,
      order: 40,
      core: true
    }.freeze,
    {
      key: :performance,
      route_key: :performance,
      active_parent_key: nil,
      label: "Performance",
      header_label: "Project performance",
      description: "Slow or failing requests and jobs",
      icon_key: :performance,
      navigation_group: :primary,
      menu_group: nil,
      order: 50,
      core: true
    }.freeze,
    {
      key: :monitors,
      route_key: :monitors,
      active_parent_key: nil,
      label: "Monitors",
      header_label: "Project monitors",
      description: "Scheduled jobs and heartbeat status",
      icon_key: :monitors,
      navigation_group: :primary,
      menu_group: nil,
      order: 60,
      core: false
    }.freeze,
    {
      key: :deployments,
      route_key: :deployments,
      active_parent_key: nil,
      label: "Deployments",
      header_label: "Project deployments",
      description: "Releases, commits, and deploy metadata",
      icon_key: :deployments,
      navigation_group: :secondary,
      menu_group: "Project tools",
      order: 70,
      core: false
    }.freeze,
    {
      key: :archives,
      route_key: :archives,
      active_parent_key: nil,
      label: "Archive search",
      header_label: "Project archive search",
      description: "Find current and archived telemetry",
      icon_key: :archive,
      navigation_group: :secondary,
      menu_group: "Project tools",
      order: 80,
      core: false
    }.freeze,
    {
      key: :settings,
      route_key: :settings,
      active_parent_key: nil,
      label: "Settings",
      header_label: "Project settings",
      description: "Setup, access, integrations, and project preferences",
      icon_key: :settings,
      navigation_group: :secondary,
      menu_group: "Manage",
      order: 90,
      core: true
    }.freeze,
    {
      key: :setup,
      route_key: :setup,
      active_parent_key: :settings,
      label: "Setup",
      header_label: "Project setup",
      description: "Connect and verify project telemetry",
      icon_key: :settings,
      navigation_group: :hidden,
      menu_group: nil,
      order: 91,
      core: true
    }.freeze,
    {
      key: :edit,
      route_key: :edit,
      active_parent_key: :settings,
      label: "Edit project",
      header_label: "Project settings",
      description: "Edit project identity",
      icon_key: :settings,
      navigation_group: :hidden,
      menu_group: nil,
      order: 92,
      core: true
    }.freeze,
    {
      key: :error_event,
      route_key: nil,
      active_parent_key: :inbox,
      label: "Issue detail",
      header_label: "Project issue",
      description: "Inspect one grouped error occurrence",
      icon_key: :inbox,
      navigation_group: :hidden,
      menu_group: nil,
      order: 93,
      core: true
    }.freeze,
    {
      key: :activity_event,
      route_key: nil,
      active_parent_key: :activity,
      label: "Event detail",
      header_label: "Project event",
      description: "Inspect one telemetry event",
      icon_key: :events,
      navigation_group: :hidden,
      menu_group: nil,
      order: 94,
      core: true
    }.freeze
  ].freeze
end
